### ISSUE TITLE
trivial_opus_dec & bucklespring

### ISSUE THREAD

**Issue by zvezdochiot** [deltabeard/trivial_opus_dec#2]
There is a cool thing, bucklespring:

https://github.com/zevv/bucklespring

But in her naked wav is used and libalure1 + libopenal1.

Ideas, how to embed trivial_opus_dec into it, is there?

**Comment by deltabeard** [comment]
I commented here: https://github.com/zevv/bucklespring/issues/74#issuecomment-453174355

It's a cool project.
